sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck:v0.5.0

script:
  - docker run --workdir=/scripts --volume $(pwd):/scripts koalaman/shellcheck:v0.5.0 -x /scripts/artifact-backup.sh
  - ./run_test.sh

matrix:
  fast_finish: true
