sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck:v0.5.0

script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck:v0.5.0 /scripts/artifact-backup.sh

matrix:
  fast_finish: true
