sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck:v0.6.0

script:
  - docker run --workdir=/work/scripts --volume $(pwd):/work koalaman/shellcheck:v0.6.0 -a -x artifact-backup.sh
  - docker run --workdir=/work/scripts --volume $(pwd):/work koalaman/shellcheck:v0.6.0 -x artifact-restore.sh
  - docker run --workdir=/work/scripts --volume $(pwd):/work koalaman/shellcheck:v0.6.0 -a -x ../run_test.sh
  - ./run_test.sh

matrix:
  fast_finish: true
